name: Create release

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Create Release and bump version files
      uses: helsingborg-stad/municipio-deploy/release-wp-plugin@feat/release-action
