name: Create release

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Release and bump version files
      uses: helsingborg-stad/release-wp-plugin-action@1.0
